### PR TITLE
Missing api key message

### PR DESCRIPTION
**Pull request by johnmedina999**
Fixes Issue #49.

### CODE REVIEW

**Comment by johnmedina999** [comment]
The issues found on CodeFactor were already there, but I didn't think it would be appropriate to fix them because you said that I should only do one thing per pull request ^_^

**Comment by abraker95** [comment]
I am most concerned about the issue saying "No name 'WebAPI' in module 'steam'". Is this a false alarm or does it really not have the class in the module?

**Comment by abraker95** [comment]
I honestly think a lot of these will simply need to be nuked. Nobody really uses them, so they are not really needed. We'll need to go through them one day and figure out what is worth keeping.

**Comment by johnmedina999** [comment]
I think that we should keep them. Just because we don't use them doesn't mean that there will never be a use for them in the future. The originating philosophy of this project was to make the biggest bot ever, with as many functions and API keys as possible; I don't think it's appropriate to veer from that. Others who decide to fork your fork may in fact need the Rocket League command, even if we don't.

**Comment by abraker95** [comment]
This is a fork of the [apex-sigma](https://gitlab.com/lu-ci/sigma/apex-sigma) bot which is more feature complete than this will ever be

**Comment by johnmedina999** [comment]
Isn't this forked from [here](https://github.com/lu-ci/apex-sigma)?

And anyway, what is your point?

**Comment by abraker95** [comment]
Yea it's forked from there, but that is archived and outdated. My point is that this bot is not something someone would want to fork given that the bot it's based on is miles ahead.

**Comment by johnmedina999** [comment]
In that case we're better off deleting this whole project and re-forking from the source.

My point is that we should strive for perfection _as if_ we were presenting this to someone who is interested in forking this project and using it as his own. With that mindset, we're pushed to write better, clearer, more concise code, with as much ease of use as possible. Which is what this Pull Request is doing: adding error handling to commands that someone might some day use.

**Comment by abraker95** [comment]
Deleting the project and re-forking will undermine the many features I implemented into the bot over the past 2 years. I would make a new bot from scratch, but there is no point in reinventing the wheel. This bot can be carved out to do what I would be able to do if I started from scratch as it has the framework for doing the things already in place.

**Pull request merged**
